OpenLMIS/openlmis-buq

Jenkinsfile, build.gradle, ci-buildImage.sh, ci-erdGeneration.sh, docker-compose.erd-generation.yml
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-383
=> TZUP-383: Set up jenkins jobs for openlmis-buq service

src/main/java/org/openlmis/buq/domain/sourceoffund/SourceOfFund.java, src/main/java/org/openlmis/buq/dto/sourceoffund/SourceOfFundDto.java, src/main/resources/db/migration/20170705125033654__initial_schema.sql, src/test/java/org/openlmis/buq/builder/SourceOfFundDataBuilder.java, src/test/java/org/openlmis/buq/domain/sourceoffund/SourceOfFundTest.java, src/test/java/org/openlmis/buq/dto/BaseDtoTest.java, src/test/java/org/openlmis/buq/dto/sourceoffund/SourceOfFundDtoTest.java
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-457
=> TZUP-457: Add Source of fund model

src/main/java/org/openlmis/buq/domain/sourceoffund/SourceOfFund.java, src/main/resources/db/migration/20170705125033654__initial_schema.sql, src/main/resources/schemas/sourceOfFund.json
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-461
=> TZUP-461: Changed SOF description to nullable

src/integration-test/java/org/openlmis/buq/web/BaseWebIntegrationTest.java, src/integration-test/java/org/openlmis/buq/web/remarks/RemarkControllerIntegrationTest.java, src/main/java/org/openlmis/buq/domain/Remark.java, src/main/java/org/openlmis/buq/domain/sourceoffund/SourceOfFund.java, src/main/java/org/openlmis/buq/dto/remark/RemarkDto.java, src/main/java/org/openlmis/buq/dto/sourceoffund/SourceOfFundDto.java, src/main/java/org/openlmis/buq/service/remark/RemarkService.java, src/main/java/org/openlmis/buq/service/remark/RemarkServiceImpl.java, src/main/java/org/openlmis/buq/web/RemarkController.java, src/main/resources/api-definition.yaml, src/main/resources/db/demo-data/buq.source_of_fund.csv, src/main/resources/db/migration/20230809134326613__add-editable-column-for-remarks.sql, src/main/resources/db/migration/20230809144127801__add-uneditable-default-remarks.sql, src/main/resources/db/migration/20230810120543327__add-editable-column-for-sof.sql, src/main/resources/db/migration/20230810120628881__add-uneditable-default-sof.sql, src/main/resources/schemas/remark.json, src/test/java/org/openlmis/buq/builder/RemarkDataBuilder.java, src/test/java/org/openlmis/buq/dto/remarks/RemarkDtoTest.java
additionally - added integration tests for remarks for Jenkins not to create unstable builds
I've also had to change the names in the demo-data of SOFs, because I was running into a duplicate name problem.
=> TZUP-516 + TZUP-517 Add predefined and uneditable remarks and sources of funds

build.gradle, src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/integration-test/resources/csv/buq_quantification_preparation_report.csv, src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantification.java, src/main/java/org/openlmis/buq/dto/csv/BottomUpQuantificationLineItemCsv.java, src/main/java/org/openlmis/buq/i18n/MessageKeys.java, src/main/java/org/openlmis/buq/service/CsvService.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/service/referencedata/OrderableReferenceDataService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml, src/main/resources/messages_en.properties, src/test/java/org/openlmis/buq/builder/OrderableDtoDataBuilder.java, src/test/java/org/openlmis/buq/service/CsvServiceTest.java, src/test/java/org/openlmis/buq/service/referencedata/OrderableReferenceDataServiceTest.java
Jira task link: https://openlmis.atlassian.net/browse/TZUP-390
=> TZUP-390: Apply logic for downloading BUQ preparation form as CSV

src/main/java/org/openlmis/buq/domain/sourceoffund/SourceOfFund.java, src/main/resources/db/demo-data/buq.source_of_fund.csv, src/test/java/org/openlmis/buq/builder/SourceOfFundDataBuilder.java, src/test/java/org/openlmis/buq/domain/sourceoffund/SourceOfFundTest.java
JIRA task links:
https://openlmis.atlassian.net/browse/TZUP-517
https://openlmis.atlassian.net/browse/TZUP-516
=> TZUP-516: Changed SOF editable default value to true

src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java
Jira task link: https://openlmis.atlassian.net/browse/TZUP-530
=> TZUP-530: Add form authorization option

src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantificationLineItem.java, src/main/java/org/openlmis/buq/dto/buq/BottomUpQuantificationLineItemDto.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/resources/db/migration/20230828095428184__add_remark_id_column_to_bottom_up_quantification_line_items_table.sql, src/main/resources/schemas/bottomUpQuantificationLineItem.json, src/test/java/org/openlmis/buq/builder/BottomUpQuantificationLineItemDataBuilder.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java
Jira task link: https://openlmis.atlassian.net/browse/TZUP-534
=> TZUP-534: Added Remark field to BottomUpQuantificationLineItem class

src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml
In a ticket it was written as `POST` method, but I assume this should be `PUT`, since we modify an existing entity.
I mark it as a draft for now, to add a few integration tests, but you can review the code now.
=> TZUP-529 Add ability to submit a BUQ

src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantification.java, src/main/java/org/openlmis/buq/exception/ValidationMessageException.java, src/main/java/org/openlmis/buq/i18n/MessageKeys.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/validate/BaseValidator.java, src/main/java/org/openlmis/buq/validate/BottomUpQuantificationValidator.java, src/main/resources/api-definition.yaml, src/main/resources/messages_en.properties, src/test/java/org/openlmis/buq/domain/buq/BottomUpQuantificationTest.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java, src/test/java/org/openlmis/buq/validate/BottomUpQuantificationValidatorTest.java
Jira task link: https://openlmis.atlassian.net/browse/TZUP-531
=> TZUP-531: Add form validation for submit and authorize

src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/validate/BottomUpQuantificationValidator.java, src/test/java/org/openlmis/buq/validate/BottomUpQuantificationValidatorTest.java
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-540
=> TZUP-540: Add form Submit & Authorize option

src/integration-test/java/org/openlmis/buq/repository/buq/BottomUpQuantificationRepositoryIntegrationTest.java, src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/i18n/MessageKeys.java, src/main/java/org/openlmis/buq/repository/buq/BottomUpQuantificationSearchParams.java, src/main/java/org/openlmis/buq/repository/buq/custom/BottomUpQuantificationRepositoryImpl.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/java/org/openlmis/buq/web/buq/QueryBottomUpQuantificationSearchParams.java, src/main/resources/messages_en.properties, src/test/java/org/openlmis/buq/builder/UserDtoDataBuilder.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java, src/test/java/org/openlmis/buq/web/buq/QueryBottomUpQuantificationSearchParamsTest.java
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-573
=> TZUP-573: Allow users to see (and perform and delete) BUQ forecasts only for their own facility

src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/ApproveFacilityForecastingStats.java, src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantification.java, src/main/java/org/openlmis/buq/repository/buq/BottomUpQuantificationRepository.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml, src/main/resources/schemas/approveFacilityForecastingStats.json, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-586
=> TZUP-586: Added GET /approveFacilityForecastingStats endpoint with logic

src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantificationStatus.java, src/main/java/org/openlmis/buq/i18n/MessageKeys.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/validate/BottomUpQuantificationValidator.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml, src/main/resources/messages_en.properties, src/test/java/org/openlmis/buq/domain/buq/BottomUpQuantificationStatusTest.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java, src/test/java/org/openlmis/buq/validate/BottomUpQuantificationValidatorTest.java, src/test/java/org/openlmis/buq/web/buq/QueryBottomUpQuantificationSearchParamsTest.java
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-592
=> TZUP-592: Add form approval option

src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java
`changeStatus` method turned out to be very slow. It's probably due to the fact that it saves the new status through the `buq.save()`, so we save the same buq with many items many times.
After doing it manually, and not calling `buq.save()` many times, the performance improved much.
=> TZUP-543 Fix performance of adding a new status change to a buq

src/main/java/org/openlmis/buq/domain/buq/BottomUpQuantification.java, src/main/java/org/openlmis/buq/dto/referencedata/SupplyLineDto.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/service/referencedata/SupplyLineReferenceDataService.java, src/main/java/org/openlmis/buq/web/buq/ApproveParams.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java
It's mostly following the two-step approval logic for the requisition.
=> TZUP-593 Add two-step buq approval logic

src/main/java/org/openlmis/buq/repository/buq/RejectionRepository.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/service/buq/RejectionService.java, src/main/java/org/openlmis/buq/service/buq/RejectionServiceImpl.java, src/test/java/org/openlmis/buq/service/buq/BottomUpQuantificationServiceTest.java
Added delete functionality for `Rejections`
=> TZUP-624: Fixed delete on BUQ with rejected status

src/integration-test/java/org/openlmis/buq/web/BaseWebIntegrationTest.java, src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/dto/role/PermissionStringDto.java, src/main/java/org/openlmis/buq/errorhandling/GlobalErrorHandling.java, src/main/java/org/openlmis/buq/exception/PermissionMessageException.java, src/main/java/org/openlmis/buq/i18n/MessageKeys.java, src/main/java/org/openlmis/buq/service/referencedata/UserReferenceDataService.java, src/main/java/org/openlmis/buq/service/role/PermissionService.java, src/main/java/org/openlmis/buq/service/role/PermissionStrings.java, src/main/java/org/openlmis/buq/util/AuthenticationHelper.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/messages_en.properties
Added functionality to check if user has got permission to call BUQ-related endpoints.
=> TZUP-499: Added rights functionality

src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java
Jira task link: https://openlmis.atlassian.net/browse/TZUP-643
=> TZUP-643: Added checkFacilityTypeAndPermission and facilities filtering

src/main/java/org/openlmis/buq/dto/productgroup/ProductGroupsCostData.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java
Added division into facility types for product groups cost data
JIRA task link: https://openlmis.atlassian.net/browse/TZUP-634
=> TZUP-634: Fixed bug with setting ID

src/integration-test/java/org/openlmis/buq/web/buq/BottomUpQuantificationControllerIntegrationTest.java, src/main/java/org/openlmis/buq/repository/buq/custom/BottomUpQuantificationRepositoryCustom.java, src/main/java/org/openlmis/buq/repository/buq/custom/BottomUpQuantificationRepositoryImpl.java, src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java, src/main/java/org/openlmis/buq/web/buq/BottomUpQuantificationController.java, src/main/resources/api-definition.yaml
JIRA task link: https://openlmis.atlassian.net/browse/OLMIS-7906
=> OLMIS-7906: Added GET bottomUpQuantifications/forFinalApproval endpoint

src/main/java/org/openlmis/buq/service/buq/BottomUpQuantificationService.java
JIRA task link: https://openlmis.atlassian.net/browse/OLMIS-7906
=> OLMIS-7906: Added facilityType and permissions check

build.gradle, build.sh, docker-compose.builder.yml, docker-compose.override.yml
Upgraded dev version to 9
JIRA task link: https://openlmis.atlassian.net/browse/OIS-44
=> OIS-44: Added transifex configuration
